// <auto-generated />
namespace AutoDealership.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class automobiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(automobiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201703221741362_automobiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
